name: Assignment Checker

on:
  workflow_dispatch: # Allows manual triggering
  push: # Trigger when code is pushed to the repository
    branches:
      - master

jobs:
  check-assignments:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run the assignment checker script
    - name: Run Assignment Checker
      run: |
        node scripts/checkAssignments.js
